function [png] = Connector_pdf() 

png.PN_name = 'Connector module';

png.set_of_Ps = {}; 
png.set_of_Ts = {'tDC1','tDC2', 'tDC3', 'tDC4', 'tDC5','tDC6','tDC_Cycle', ...
    'tDC_Bike', 'tDC_Car'};  % dummy connector trans

png.set_of_As = {
    'pOUT','tDC1', 1, ... % Connecting Order Generator with Foodora Hub
    'tDC1','pOrder', 1, ...
    'pConfirm','tDC2', 1, ... % Connecting Resturant with Rider Resturant
    'tDC2','pOrder_Recive', 1, ...
    'pNotify_Rider','tDC3', 1, ... % Connecting Foodora Hub with Rider Check
    'tDC3','pRi_Order_Recive', 1, ...
    'pOrder_Complete', 'tDC4', 1, ... % Connecting Resturant with Food Delivering
    'tDC4', 'pOrders_From_Res', 1, ...
    'pRider_Reach_Restur', 'tDC5', 1, ... % Connecting Rider Check with Food Delivering
    'tDC5', 'pRiders_At_Res', 1, ...
    'pOrder_Reject', 'tDC6', 1, ... % Connecting Rider Check with Food Delivering
    'tDC6', 'pReject_Order', 1, ...
    'pCycle_Back', 'tDC_Cycle', 1, ...
    'tDC_Cycle', 'pCycles', 1, ...
    'pBike_Back', 'tDC_Bike', 1, ...
    'tDC_Bike', 'pBikes', 1, ...
    'pCar_Back', 'tDC_Car', 1, ...
    'tDC_Car', 'pCars', 1, ...
    };