% Food Delivering pdf
function [png] = Food_Delivering_pdf() 

png.PN_name='Food Delivering';

% Places in Food Delivering Module
png.set_of_Ps = {'pOrders_From_Res','pOrder_Fr_Cycle','pOrder_Fr_Bike', ...
    'pOrder_Fr_Car' , 'pRiders_At_Res', 'pCycle_Travel_Des', ...
    'pBike_Travel_Des', 'pCar_Travel_Des', 'pCycle_Reach_Des', ...
    'pBike_Reach_Des','pCar_Reach_Des', 'pCycle_Back', 'pBike_Back', ...
    'pCar_Back'};

% Transitions in Food Delivering Module
png.set_of_Ts = {'tOrder_Fr_Cycle','tOrder_Fr_Bike', 'tOrder_Fr_Car',...
    'tCycle_Rider', 'tBike_Rider', 'tCar_Rider', ...
    'tCycle_Travel_Des', 'tBike_Travel_Des', 'tCar_Travel_Des', ...
    'tCycle_Travel_Back','tBike_Travel_Back','tCar_Travel_Back'};

% Arcs in Food Delivering Module
png.set_of_As = {
    'pOrders_From_Res', 'tOrder_Fr_Cycle', 1, ...  % Selecting Order for Rider
    'tOrder_Fr_Cycle', 'pOrder_Fr_Cycle', 1, ...
    'pOrder_Fr_Cycle', 'tCycle_Rider', 1, ...
    'pRiders_At_Res', 'tCycle_Rider', 1, ... % Selecting Cycle Rider to deliver food 
    'tCycle_Rider', 'pCycle_Travel_Des', 1, ...
    'pCycle_Travel_Des', 'tCycle_Travel_Des', 1, ...
    'tCycle_Travel_Des', 'pCycle_Reach_Des', 1, ...
    'pCycle_Reach_Des', 'tCycle_Travel_Back', 1, ...
    'tCycle_Travel_Back', 'pCycle_Back', 1, ...
    'pOrders_From_Res', 'tOrder_Fr_Bike', 1, ...% Selecting Bike Rider to deliver food 
    'tOrder_Fr_Bike', 'pOrder_Fr_Bike', 1, ...
    'pOrder_Fr_Bike', 'tBike_Rider', 1, ...
    'pRiders_At_Res', 'tBike_Rider', 1, ... 
    'tBike_Rider', 'pBike_Travel_Des', 1, ...    
    'pBike_Travel_Des', 'tBike_Travel_Des', 1, ...
    'tBike_Travel_Des', 'pBike_Reach_Des', 1, ...
    'pBike_Reach_Des', 'tBike_Travel_Back', 1, ...
    'tBike_Travel_Back', 'pBike_Back', 1, ...
    'pOrders_From_Res', 'tOrder_Fr_Car', 1, ... % Selecting Car Rider to deliver food 
    'tOrder_Fr_Car', 'pOrder_Fr_Car', 1, ...
    'pOrder_Fr_Car', 'tCar_Rider', 1, ...
    'pRiders_At_Res', 'tCar_Rider', 1, ... 
    'tCar_Rider', 'pCar_Travel_Des', 1, ...
    'pCar_Travel_Des', 'tCar_Travel_Des', 1, ...
    'tCar_Travel_Des', 'pCar_Reach_Des', 1, ...
    'pCar_Reach_Des', 'tCar_Travel_Back', 1, ...
    'tCar_Travel_Back', 'pCar_Back', 1, ...
    };