% Example-18: foodora hub pdf
function [png] = Foodora_Hub_pdf() 

png.PN_name='Foodora HUB';

png.set_of_Ps = {'pOrder', 'pConfirm', 'pReject_Order', 'pRejected_Order'};
png.set_of_Ts = {'tRes_Open','tRes_close', 'tNotify_Cust'}; 
png.set_of_As = {'pOrder','tRes_Open',1,...
    'pOrder','tRes_close',1,...
    'tRes_close', 'pReject_Order',1,...
    'tRes_Open','pConfirm',1,...
    'pReject_Order', 'tNotify_Cust',1,...
    'tNotify_Cust', 'pRejected_Order',1,...
    };