% Resturant pdf
function [png] = Resturant_pdf() 

png.PN_name='Resturant';

png.set_of_Ps = {'pOrder_Recive', 'pOrder_Wait','pNotify_Rider' ,'pOrder_Process', ...
    'pRes_Resource','pRes_Capacity', 'pOrder_Complete', 'pOrder_Reject'};

png.set_of_Ts = {'tAccept','tReject', 'tStart_preparation', ...
    'tComplete_Order','tRes_Capacity_Reset'}; 

png.set_of_As = {
    'pOrder_Recive','tAccept',1,... 
    'pOrder_Recive','tReject',1,...
    'tReject', 'pOrder_Reject',1,...
    'tAccept','pOrder_Wait',1,...
    'tAccept','pNotify_Rider',1,...
    'pOrder_Wait','tStart_preparation',1,...
    'tStart_preparation','pOrder_Process',1,...
    'pOrder_Process','tComplete_Order',1,...
    'tComplete_Order','pRes_Resource',1,...
    'pRes_Resource','tRes_Capacity_Reset',1,...
    'tRes_Capacity_Reset','pRes_Capacity',1,...
    'pRes_Capacity','tStart_preparation',1,...
    'tComplete_Order','pOrder_Complete',1,...
    };