%Foodora hub pdf
function [png] = Rider_Check_pdf() 

png.PN_name='Rider Check';

png.set_of_Ps = {
    'pRi_Order_Recive', 'pOrder_for_Cycle', 'pOrder_for_Bike', ...
    'pOrder_for_Car','pCycle_GEN' ,'pCycles', 'pBike_GEN','pBikes',...
    'pCar_GEN','pCars', 'pRider_Res_Travel', ...
    'pRider_Reach_Restur' };

png.set_of_Ts = {
    'tOrder_for_Cycle','tOrder_for_Bike','tOrder_for_Car', ...
    'tCycle_Accept', 'tCycle_Reject', ...
    'tBike_Accept', 'tBike_Reject', 'tCar_Accept', 'tCar_Reject', ...
    'tCycle_GEN','tBike_GEN','tCar_GEN','tRider_Res_Travel'};

png.set_of_As = {
    'pRi_Order_Recive', 'tOrder_for_Cycle', 1, ...   
    'pRi_Order_Recive', 'tOrder_for_Bike', 1, ... %Output Arcs from Distance Checker
    'pRi_Order_Recive', 'tOrder_for_Car', 1, ...
    'tOrder_for_Cycle', 'pOrder_for_Cycle', 1, ...
    'tOrder_for_Bike', 'pOrder_for_Bike', 1, ...
    'tOrder_for_Car', 'pOrder_for_Car', 1, ...
    'pOrder_for_Cycle', 'tCycle_Accept', 1, ... %Output Arcs from Rider for Cycle
    'pOrder_for_Cycle', 'tCycle_Reject', 1, ...
    'tCycle_Reject', 'pRi_Order_Recive', 1, ... %Output Arc for rejected order from Cycle 
    'pCycles', 'tCycle_Accept', 1, ...
    'pOrder_for_Bike', 'tBike_Accept', 1, ... %Output Arcs from Rider for Bike
    'pOrder_for_Bike', 'tBike_Reject', 1, ...
    'tBike_Reject', 'pOrder_for_Cycle', 1, ... %Output Arc for rejected order from Bike 
    'pBikes', 'tBike_Accept', 1, ...
    'pOrder_for_Car', 'tCar_Accept', 1, ... %Output Arcs from Rider for Car
    'pOrder_for_Car', 'tCar_Reject', 1, ...
    'tCar_Reject', 'pOrder_for_Bike', 1, ... %Output Arc for rejected order from Car 
    'pCars', 'tCar_Accept', 1, ...
    'tCycle_Accept', 'pRider_Res_Travel', 1, ... %Output Arc from Acepted Orders
    'tBike_Accept', 'pRider_Res_Travel', 1, ...
    'tCar_Accept', 'pRider_Res_Travel', 1, ...
    'pRider_Res_Travel', 'tRider_Res_Travel', 1, ...
    'tRider_Res_Travel', 'pRider_Reach_Restur', 1, ...
    'pCycle_GEN', 'tCycle_GEN', 1, ...
    'tCycle_GEN', 'pCycles', 1, ...
    'pBike_GEN', 'tBike_GEN', 1, ...
    'tBike_GEN', 'pBikes', 1, ...
    'pCar_GEN', 'tCar_GEN', 1, ...
    'tCar_GEN', 'pCars', 1 };